// import {
// 	Code2,
// 	Database,
// 	GraduationCap,
// 	MessageSquare,
// 	Network,
// 	Cloud,
// 	Smartphone,
// 	Brain,
// 	BarChart2,
// 	Layers,
// 	Shield,
// 	Server,
// } from "lucide-react";

// import Track from "./types";

// export const Tracks: Track[] = [
// 	{
// 		id: "frontend",
// 		name: "Frontend Development",
// 		category: "Engineering",
// 		difficulty: "Intermediate",
// 		description:
// 			"React, TypeScript, CSS architecture, performance optimization, and accessibility for modern web roles.",
// 		duration: "40 min",
// 		questions: 8,
// 		tags: ["React", "TypeScript", "CSS", "Performance"],
// 		icon: Code2,
// 		popular: true,
// 		completions: 18420,
// 	},
// 	{
// 		id: "backend",
// 		name: "Backend Development",
// 		category: "Engineering",
// 		difficulty: "Intermediate",
// 		description:
// 			"REST APIs, databases, caching strategies, microservices, and distributed system fundamentals.",
// 		duration: "45 min",
// 		questions: 8,
// 		tags: ["Node.js", "SQL", "Redis", "APIs"],
// 		icon: Database,
// 		popular: true,
// 		completions: 15680,
// 	},
// 	{
// 		id: "behavioral",
// 		name: "Behavioral & STAR",
// 		category: "Behavioral",
// 		difficulty: "Beginner",
// 		description:
// 			"Master the STAR method for leadership, collaboration, conflict resolution, and growth-oriented stories.",
// 		duration: "35 min",
// 		questions: 10,
// 		tags: ["STAR", "Leadership", "Conflict", "Growth"],
// 		icon: MessageSquare,
// 		completions: 22100,
// 		isNew: true,
// 	},
// 	{
// 		id: "internship",
// 		name: "Internship Ready",
// 		category: "Entry Level",
// 		difficulty: "Beginner",
// 		description:
// 			"Tailored for CS students. Core DSA, OOP principles, and project walkthroughs at junior level.",
// 		duration: "30 min",
// 		questions: 7,
// 		tags: ["DSA", "OOP", "Projects", "Fundamentals"],
// 		icon: GraduationCap,
// 		completions: 31400,
// 		popular: true,
// 	},
// 	{
// 		id: "system-design",
// 		name: "System Design",
// 		category: "System Design",
// 		difficulty: "Advanced",
// 		description:
// 			"Scale distributed systems, design URL shorteners, messaging queues, feeds, and storage systems.",
// 		duration: "60 min",
// 		questions: 5,
// 		tags: ["Scalability", "CAP", "Databases", "Caching"],
// 		icon: Network,
// 		isPro: true,
// 		completions: 9840,
// 	},
// 	{
// 		id: "devops",
// 		name: "DevOps & Cloud",
// 		category: "Specialized",
// 		difficulty: "Advanced",
// 		description:
// 			"CI/CD pipelines, containerization, Kubernetes, cloud infra (AWS/GCP), and SRE practices.",
// 		duration: "50 min",
// 		questions: 8,
// 		tags: ["Docker", "K8s", "AWS", "CI/CD"],
// 		icon: Cloud,
// 		isPro: true,
// 		isNew: true,
// 		completions: 4210,
// 	},
// 	{
// 		id: "mobile",
// 		name: "Mobile Development",
// 		category: "Specialized",
// 		difficulty: "Intermediate",
// 		description:
// 			"iOS (Swift/SwiftUI) and Android (Kotlin/Compose) — architecture patterns, performance, and platform APIs.",
// 		duration: "45 min",
// 		questions: 8,
// 		tags: ["Swift", "Kotlin", "iOS", "Android"],
// 		icon: Smartphone,
// 		isPro: true,
// 		completions: 6730,
// 	},
// 	{
// 		id: "data-structures",
// 		name: "Data Structures & Algorithms",
// 		category: "Engineering",
// 		difficulty: "Intermediate",
// 		description:
// 			"Arrays, trees, graphs, dynamic programming, and sorting — exactly what FAANG rounds test.",
// 		duration: "50 min",
// 		questions: 6,
// 		tags: ["Arrays", "Trees", "Graphs", "DP"],
// 		icon: Brain,
// 		completions: 27890,
// 		popular: true,
// 	},
// 	{
// 		id: "data-science",
// 		name: "Data Science & ML",
// 		category: "Specialized",
// 		difficulty: "Advanced",
// 		description:
// 			"Feature engineering, model evaluation, statistics, SQL analytics, and ML system design questions.",
// 		duration: "55 min",
// 		questions: 8,
// 		tags: ["Python", "ML", "SQL", "Statistics"],
// 		icon: BarChart2,
// 		isPro: true,
// 		completions: 7150,
// 	},
// 	{
// 		id: "fullstack",
// 		name: "Full Stack Engineer",
// 		category: "Engineering",
// 		difficulty: "Advanced",
// 		description:
// 			"End-to-end engineering depth: auth flows, database modeling, API design, and client-side architecture.",
// 		duration: "55 min",
// 		questions: 9,
// 		tags: ["React", "Node.js", "Auth", "Databases"],
// 		icon: Layers,
// 		isPro: true,
// 		isNew: true,
// 		completions: 5480,
// 	},
// 	{
// 		id: "security",
// 		name: "Security Engineering",
// 		category: "Specialized",
// 		difficulty: "Advanced",
// 		description:
// 			"OWASP top 10, threat modeling, secure coding, penetration testing concepts and incident response.",
// 		duration: "45 min",
// 		questions: 8,
// 		tags: ["OWASP", "Auth", "Encryption", "Threats"],
// 		icon: Shield,
// 		isPro: true,
// 		completions: 3290,
// 	},
// 	{
// 		id: "backend-advanced",
// 		name: "Senior Backend",
// 		category: "Engineering",
// 		difficulty: "Advanced",
// 		description:
// 			"Concurrency, event-driven architecture, database internals, performance tuning, and technical leadership.",
// 		duration: "60 min",
// 		questions: 9,
// 		tags: ["Concurrency", "Events", "DB Internals", "Scale"],
// 		icon: Server,
// 		isPro: true,
// 		completions: 8640,
// 	},
// ];

export const CATEGORIES = [
	"All",
	"Engineering",
	"Behavioral",
	"System Design",
	"Entry Level",
	"Specialized",
];
export const DIFFICULTIES = ["All", "Beginner", "Intermediate", "Advanced"];

export const DIFFICULTY_COLORS = {
	Beginner: { bg: "rgba(16,185,129,0.10)", color: "#10B981" },
	Intermediate: { bg: "rgba(245,158,11,0.10)", color: "#F59E0B" },
	Advanced: { bg: "rgba(239,68,68,0.10)", color: "#F87171" },
};
